[build]
builder = "RAILPACK"
buildCommand = "python manage.py collectstatic --noinput"

[deploy]
startCommand = "gunicorn voucher_system.wsgi:application --bind 0.0.0.0:$PORT"

[[volumes]]
mountPath = "/app/media"
volumeName = "voucher-media"